language: python
services:
  - mongodb
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install selenium pyvirtualdisplay coverage"
  - export DJANGO_SETTINGS_MODULE="echaloasuerte.settings.test"
  - "python manage.py syncdb --noinput"
# command to run tests
script:
  - nosetests tests/test_init.py tests -v
#  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && "${TRAVIS_PULL_REQUEST}" == "false" ]]; then pip install sauceclient && nosetests func_test -v ; fi
